# Generated by Django 5.2.1 on 2025-05-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_scientificidea_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificidea',
            name='file',
        ),
    ]
