# Generated by Django 5.2.1 on 2025-07-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificidea',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='scientific_idea_files/'),
        ),
    ]
