# Generated by Django 5.2.1 on 2025-08-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
