# Generated by Django 5.2.1 on 2025-05-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverificationcode',
            name='user',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(default='omidszce@gmail.com', max_length=254, unique=True),
        ),
    ]
