# Generated by Django 5.2.1 on 2025-05-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_emailverificationcode_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
