# Generated by Django 5.2.1 on 2025-05-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_emailverificationcode_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='email',
            field=models.EmailField(default='omidszce@gmail.com', max_length=254, unique=True),
        ),
    ]
